name: Build and release Melt Systemd sysext images
on:
  push:
    tags:
      - 'latest'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4
        with:
          path: furnace

      # prepare build host
      - name: install prerequisites
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

      - name: build release artifacts
        run: |
          pushd furnace
          ./build_release.sh

      - name: delete previous latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pushd furnace
          gh release delete latest --cleanup-tag

      - name: create a new latest release with all artifacts
        uses: softprops/action-gh-release@v1
        with:
          body_path: furnace/Release.md
          files: |
            furnace/SHA256SUMS
            furnace/*.raw
            furance/*.conf

       - name: prepare r2 upload dir
        run: |
          mkdir r2
          mv *.raw r2/
          mv SHA256SUMS r2/

      - name: Upload files to R2
        uses: willfurstenau/r2-dir-upload@main
        with:
          accountid: ${{ secrets.R2_ACCOUNT_ID_MELT_PUBLIC_ASSETS }}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID_MELT_PUBLIC_ASSETS }}
          secretaccesskey: ${{ secrets.R2_ACCESS_SECRET_KEY_MELT_PUBLIC_ASSETS }}
          bucket: 'melt-public-assets'
          source: 'furnace/r2'
          destination: '/sysext'
