name: Build and release Melt Systemd sysext images
on:
  push:
    tags:
      - 'latest'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4
        with:
          path: furnace

      # prepare build host
      - name: install prerequisites
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

      - name: build release artifacts
        run: |
          pushd furnace
          ./build_release.sh

      - name: delete previous latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pushd furnace
          gh release delete latest --cleanup-tag

      - name: create a new latest release with all artifacts
        uses: softprops/action-gh-release@v1
        with:
          body_path: furnace/Release.md
          files: |
            furnace/SHA256SUMS
            furnace/*.raw
            furance/*.conf
      - name: Upload files to R2
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT_MELT_PUBLIC_ASSETS }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID_MELT_PUBLIC_ASSETS }}
          secret_access_key: ${{ secrets.R2_ACCESS_SECRET_KEY_MELT_PUBLIC_ASSETS }}
          bucket: melt-public-assets
          file: furnace/*.raw
          destination: '/sysext'
